#pragma once
#include "usb_hid_keys.h"
#include <stdint.h>

uint8_t keymap[8][8] = {
    {KEY_1, KEY_ESC, KEY_TAB, KEY_ESC, KEY_SPACE, KEY_LEFTALT, KEY_Q, KEY_2},
    {KEY_3, KEY_W, KEY_A, KEY_LEFTSHIFT, KEY_Z, KEY_S, KEY_E, KEY_4},
    {KEY_5, KEY_R, KEY_D, KEY_X, KEY_C, KEY_F, KEY_T, KEY_6},
    {KEY_7, KEY_Y, KEY_G, KEY_V, KEY_B, KEY_H, KEY_U, KEY_8},
    {KEY_9, KEY_I, KEY_J, KEY_N, KEY_M, KEY_K, KEY_O, KEY_0},
    {KEY_EQUAL, KEY_P, KEY_L, KEY_COMMA, KEY_DOT, KEY_SEMICOLON, KEY_LEFTBRACE,
     KEY_MINUS},
    {KEY_BACKSLASH, KEY_RIGHTBRACE, KEY_APOSTROPHE, KEY_SLASH, KEY_RIGHTSHIFT,
     KEY_PAGEDOWN, KEY_HOME},
    {KEY_BACKSPACE, KEY_ENTER, KEY_LEFT, KEY_DOWN, KEY_F1, KEY_F3, KEY_F5,
     KEY_7},
};
